### PR TITLE
Mpi backup

### LINKED ISSUE #62: MPI_IAllgather backup plan
Many machines still use versions of MPI without non blocking collectives. While the use of IAllgather (and Iallgatherv) is important for maximizing performance on new machines, having a backup routine that allows NTPoly to run on more machines would be helpful.

Probably the simplest solution is to just build a replacement routine, and then add a compile time switch between the two. The replacement routine would have to be based on isend/irecv. Using the blocking all gather isn't an option because any implementation that doesn't have non-blocking collectives probably doesn't have anything like `MPI_THREAD_SERIALIZED`, so we'd lose all the overlapping of communication and computation.

### PR DESCRIPTION
**Pull request by william-dawson**
Fixes #62 .

Optionally replaces the MPI_IAllgather with a sequence of send and receives.

I also took this opportunity to perform an optimization of the MPI communication inside the matrix reduce module.

### CODE REVIEW

**Comment by william-dawson** [comment]
@vyu16 @wphuhn would you mind testing my proposed fix (which is in the MPIBackup branch) with ELSI and the ELSI build system? Inside the MatrixReduceModule there is a a macro `NOIALLGATHER`, which if set will trigger the backup plan. 

When building NTPoly with my build system, one can pass -DNOIALLGATHER=Yes to CMake. However, I know you have your own NTPoly build system for ELSI which seems to avoid macros, so please let me know if this macro solution has any problems.

**Comment by vyu16** [comment]
@william-dawson Thanks for the fix! I'm testing it now, because I want to get rid of my workaround in FHI-aims as early as possible. I didn't see any problem with the build system. I'll let you know how it works. Btw, is version 2.0 ready in general?

**Comment by william-dawson** [comment]
@vyu16 Great. Once you've confirmed things on your end I will merge this pull request.

2.0 is ready in general, please feel free to use it. I'll prepare a proper release soon.

**Comment by vyu16** [comment]
@william-dawson I made the new code into ELSI and tested it within both ELSI and FHI-aims. So far it's working as expected. I haven't looked at the performance difference on a large scale.

**Pull request merged**
